<?php
/**
 * 404 Template
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
get_header();
?>

<div class="container">
    <div class="row">
        <div class="container span8 offset1"
             <header class="entry-header">
                <div class="ribbon-top">
                    <h1 class="entry-title" style="color: #e9ecc9">Siden kan ikke vises - Error 404</h1>
                </div>
            </header>
            <table table-bordeless>
                <tbody>
                    <tr>
                        <td>
                            <h3>Siden er enten blevet flyttet, eller slettet. Gå til startsiden</h3>
                        </td>               
                        <td>
                            <img src="<?php echo "http://" . getenv('HTTP_HOST') . "/spisetid/wp-content/uploads/2016/12/aubergine-168x300.png" ?>">
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>

<?php get_footer(); ?>